/* Generated by run.py. Edit the task JSON, not this generated model.
   One d_step = one logical moment. TRACE is printed only during replay. */
$declarations

init {
$body
}

ltl check { $formula }
